In [ ]:
%load_ext autoreload 
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [ ]:
import torch
from rnn_reserving.config import TrainingConfig, ModelConfig
from rnn_reserving.dataloader import make_loaders

from rnn_reserving.models import GRUInsurance
from typing import Dict
from rnn_reserving.trainer import Trainer

In [ ]:
config = TrainingConfig(
    batch_size=32,
    shuffle_train=True,
    early_stopping_patience=10,
    use_wandb=True, # set to false for debugging
    run_name="Baseline_GRU_v1",
    run_notes="Basic GRU model. One feature, one target. No company codes. Default parameters",
    data_debug=False,
    pad_value=-1.0,
)

model_config = ModelConfig()


In [4]:
train_loader, val_loader = make_loaders(config)

In [5]:
model = GRUInsurance(model_config)

In [ ]:
def _get_mask(target, pred, pad_value):
    mask = (target != pad_value).float()
    while mask.dim() < pred.dim():
        mask = mask.unsqueeze(-1)
    return mask

class MaskedLoss:
    """General masked loss function that can handle both MSE and MAE based on the provided loss type."""
    LOSSES = {
        'mse': lambda p, t: (p - t) ** 2,
        'mae': lambda p, t: torch.abs(p - t),
        # add more losses here if needed...
    }
    
    def __init__(self, loss: str = 'mse', pad_value: float = -1.0):
        if loss not in self.LOSSES:
            raise ValueError(f"loss must be one of {list(self.LOSSES.keys())}")
        self.loss_fn = self.LOSSES[loss]
        self.pad_value = pad_value
    
    def __call__(self, pred, target):
        mask = _get_mask(target, pred, self.pad_value)
        return (self.loss_fn(pred, target) * mask).sum() / mask.sum()


def metrics_fn(output: torch.Tensor, target: torch.Tensor, pad_value: float = -1.0) -> Dict[str, float]:
    return {
        name: MaskedLoss(name, pad_value)(output, target).item()
        for name in ['mse', 'mae']
    }


criterion = MaskedLoss(loss='mse', pad_value=config.pad_value)
optimiser = torch.optim.Adam(model.parameters(), lr=config.learning_rate)
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimiser, T_max=50)

In [ ]:
trainer = Trainer(
    model,
    train_loader,
    val_loader,
    criterion,
    optimiser,
    config,
    scheduler=scheduler,
    metrics_fn=metrics_fn,
)

In [ ]:
trainer.train()


In [ ]:
trainer.model.eval()
with torch.no_grad():
    for batch in val_loader:
        inputs, lengths, targets, ids = batch['inputs'], batch['lengths'], batch['targets'], batch['ids']
        outputs = trainer.model(inputs, lengths)
        print("Outputs:", outputs)
        print("Targets:", targets)
        break  # just look at the first batch

inputs[0], outputs[0], targets[0]

(tensor([[ 0.3447],
         [ 0.8259],
         [ 1.1683],
         [ 1.3732],
         [ 1.4595],
         [ 1.4846],
         [-1.0000],
         [-1.0000],
         [-1.0000]]),
 tensor([ 0.7151,  1.0250,  1.0448,  1.0077,  0.9844,  0.9741, -0.0435, -0.0435,
         -0.0435]),
 tensor([ 1.4880,  1.4879, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000,
         -1.0000]))